set search_path = "nomenclatures";
 
--commune
--delete from commune;
--select * from commune;
INSERT INTO commune (insee,nomofficiel,parent_insee) values ('001','Talmont','AR1');
INSERT INTO commune (insee,nomofficiel,parent_insee) values ('002','Nouméa','AR1');
INSERT INTO commune (insee,nomofficiel,parent_insee) values ('44001','Toulouse','AR3');
INSERT INTO commune (insee,nomofficiel,parent_insee) values ('44002','Muret','AR3');
INSERT INTO commune (insee,nomofficiel,parent_insee) values ('44003','Saint Gaudens','AR3');
INSERT INTO commune (insee,nomofficiel,parent_insee) values ('44004','Luchon','AR3');

-- ARRONDISSEMENT
--delete from ARRONDISSEMENT ;
--select * from ARRONDISSEMENT ;
INSERT INTO ARRONDISSEMENT (insee,nomofficiel,parent_insee) values ('AR1','ARRONDISSEMENT de Talmont','65');
INSERT INTO ARRONDISSEMENT (insee,nomofficiel,parent_insee) values ('AR2','ARRONDISSEMENT de Nouméa','31');
INSERT INTO ARRONDISSEMENT (insee,nomofficiel,parent_insee) values ('AR3','ARRONDISSEMENT du grand Haute Garonne','31');

-- DEPARTEMENT
--delete from DEPARTEMENT ;
INSERT INTO DEPARTEMENT (insee,nomofficiel,parent_insee) values ('31','Haute Garonne','73');
INSERT INTO DEPARTEMENT (insee,nomofficiel,parent_insee) values ('65','Haute Pyrénées','73');

-- REGION
--delete from REGION ;
INSERT INTO REGION (insee,nomofficiel,parent_insee) values ('73','Midi-Pyrénées','');

--APPROBATIONS
DELETE FROM nomenclatures.ref_approbation where rappr_uti_crea_lb='création jdd usagers';
--select * FROM nomenclatures.ref_approbation order by 10;
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANTRANSPP','A','TPRO01','Agrément communautaire transformation de produits de la pêche','Agrément communautaire transformation de produits ',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AS_CE_HLMRCR','B','TPRO02','Agrément communautaire halle à marée / première vente ','Agrément communautaire halle à marée / première ve',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AG_CEE_MGPPC','C','TPRO01','Agrément communautaire marché de gros produits de la pêche et coquillages ','Agrément communautaire marché de gros produits de ',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AG_CEE_NVRCG','V','TPRO02','Agrément communautaire navire congélateur','Agrément communautaire navire congélateur',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AG_NVREXP','A','TPRO01','Agrément communautaire navire expéditeur de coquillages','Agrément communautaire navire expéditeur de coquil',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANEMBOE','B','TPRO02','AS centre d emballage d oeufs - communautaire','AS centre d emballage d oeufs - communautaire',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASCCC','C','TPRO01','AS cuisine centrale - communautaire','AS cuisine centrale - communautaire',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANENTR','V','TPRO02','Agrément communautaire  entrepôt','Agrément communautaire  entrepôt',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGR_ESVEBO','A','TPRO01','AS estomac,vessie, boyau séché ou salé <> chauffé - communautaire','AS estomac,vessie, boyau séché ou salé <> chauffé ',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANEXPCOQ','B','TPRO02','Agrément communautaire expédition de coquillages','Agrément communautaire expédition de coquillages',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANGELAT','C','TPRO01','AS gélatine – communautaire','AS gélatine – communautaire',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANGREXPR','V','TPRO02','AS graisses, extraits de viandes et issues - communautaire','AS graisses, extraits de viandes et issues - commu',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANLPL','A','TPRO01','AS lait et produits laitiers – communautaire','AS lait et produits laitiers – communautaire',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASMANIPCGRC','B','TPRO02','Agrément communautaire transformation cuisses de grenouille','Agrément communautaire transformation cuisses de g',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASMANIPESCC','C','TPRO01','Agrément communautaire transformation d escargot','Agrément communautaire transformation descargot',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANMANIPPP','V','TPRO02','Agrément communautaire manipulation de produits de la pêche','Agrément communautaire manipulation de produits de',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AS_NAVUS','A','TPRO01','Agrément communautaire navire usine','Agrément communautaire navire usine',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANOVOP','B','TPRO02','AS ovoproduits – communautaire','AS ovoproduits – communautaire',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSAABPALFER','C','TPRO01','AS palmipèdes gras - salle d abattage à la ferme - communautaire','AS palmipèdes gras - salle d abattage à la ferme -',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANPREVDE','V','TPRO02','AS préparation de viandes - communautaire','AS préparation de viandes - communautaire',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANPRODVDE','A','TPRO01','AS produits à base de viande - communautaire','AS produits à base de viande - communautaire',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANPURCOQ','B','TPRO02','Agrément communautaire purification de coquillages','Agrément communautaire purification de coquillages',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANTRAVFC','C','TPRO01','AS transformation viandes faible capacité - communautaire','AS transformation viandes faible capacité - commun',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANABBOU','V','TPRO02','AS viandes fraîches boucherie - abattage - communautaire','AS viandes fraîches boucherie - abattage - communa',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASVFBDCOMMUN','A','TPRO01','AS viandes fraîches boucherie - découpe - communautaire','AS viandes fraîches boucherie - découpe - communau',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASVFBDDEROG','B','TPRO02','AS viandes fraîches boucherie - découpe - dérogataire','AS viandes fraîches boucherie - découpe - dérogata',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANABGIBEL','C','TPRO01','AS viandes fraîches gib ongulé élevage - abattage - communautaire','AS viandes fraîches gib ongulé élevage - abattage ',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANDCGIBEL','V','TPRO02','AS viandes fraîches gib ongulé élevage - découpe - communautaire','AS viandes fraîches gib ongulé élevage - découpe -',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASVFGSDC','A','TPRO01','AS viandes fraîches gibier sauvage - découpe - communautaire','AS viandes fraîches gibier sauvage - découpe - com',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGC_TTGIBS','B','TPRO02','AS viandes fraîches gibier sauvage - traitement - communautaire','AS viandes fraîches gibier sauvage - traitement - ',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANLAPELE','C','TPRO01','AS viandes fraîches lapin, ptt gib élev poils - abattage - commun','AS viandes fraîches lapin, ptt gib élev poils - ab',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASVFLPGEPAD' ,'V','TPRO02','AS viandes fraîches lapin, ptt gib élev poils - abattage - déroga','AS viandes fraîches lapin, ptt gib élev poils - ab',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASVFLPGEPDC','A','TPRO01','AS viandes fraîches lapin, ptt gib élev poils - découpe - commun','AS viandes fraîches lapin, ptt gib élev poils - dé',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASVFLPGEPDD' ,'B','TPRO02','AS viandes fraîches lapin, ptt gib élev poils - découpe - déroga','AS viandes fraîches lapin, ptt gib élev poils - dé',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASVFVGEPAC','C','TPRO01','AS viandes fraîches volaille, gib élev plumes - abattage - commun','AS viandes fraîches volaille, gib élev plumes - ab',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('ASVFVGPDC','V','TPRO02','AS viandes fraîches volaille, gib élev plumes - découpe - commun','AS viandes fraîches volaille, gib élev plumes - dé',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AGSANVDEHACH','A','TPRO01','AS viandes hachées - communautaire','AS viandes hachées - communautaire',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AUTCOL72H','B','TPRO02','Autorisation de collecte à 72 heures','Autorisation de collecte à 72 heures',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AS_GROS ','C','TPRO01','Agrément CEE marché de gros (hors produits de la pêche et coquillages) ','Agrément CEE marché de gros (hors produits de la p',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('AS_MANIPV ','V','TPRO02','Agrément CEE reconditionnement ','Agrément CEE reconditionnement ',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('DERAGRESC','A','TPRO01','Dérogation agrément Escargots','Dérogation agrément Escargots',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('DERAGRPVB','B','TPRO02','Dérogation agrément PBV, PC, saucisse crue, chair saucisse et PV','Dérogation agrément PBV, PC, saucisse crue, chair ',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('DERAGRPL','C','TPRO01','Dérogation agrément Produits laitiers','Dérogation agrément Produits laitiers',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('DERAGRPNTP','V','TPRO02','Dérogation agrément Produits non transformés de la pêche','Dérogation agrément Produits non transformés de la',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('DERAGRPTP','A','TPRO01','Dérogation agrément Produits transformés de la pêche','Dérogation agrément Produits transformés de la pêc',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('DERAGRRRP','B','TPRO02','Dérogation agrément Repas, fractions avec produits (A3-AM 8/6/06)','Dérogation agrément Repas, fractions avec produits',now(),now(),'création jdd usagers','création jdd usagers');
INSERT INTO nomenclatures.ref_approbation (rappr_rfa, sa_rfa, tappr_rfa, rappr_lb, rappr_court_lb, rappr_deb_dt,rappr_crea_dt , rappr_uti_crea_lb,rappr_uti_crea_log) values ('DERAGRVFB','C','TPRO01','Dérogation agrément Viande fraîche boucherie hors viande hachée','Dérogation agrément Viande fraîche boucherie hors ',now(),now(),'création jdd usagers','création jdd usagers');

--CAMPAGNE
DELETE FROM nomenclatures.campagne
INSERT INTO campagne (camp_rfa, camp_lb, camp_com_lb, camp_deb_dt, camp_fin_dt, camp_crea_dt, camp_uti_crea_lb, camp_uti_crea_log, camp_modif_dt, camp_uti_modif_lb, camp_uti_modif_log) VALUES ('2013', '2013', NULL, '2014-06-18', NULL, '2014-06-18', 'création jdd usagers', 'création jdd usagers', NULL, NULL, NULL);
INSERT INTO campagne (camp_rfa, camp_lb, camp_com_lb, camp_deb_dt, camp_fin_dt, camp_crea_dt, camp_uti_crea_lb, camp_uti_crea_log, camp_modif_dt, camp_uti_modif_lb, camp_uti_modif_log) VALUES ('2014', '2014', NULL, '2014-06-18', NULL, '2014-06-18', 'création jdd usagers', 'création jdd usagers', NULL, NULL, NULL);
INSERT INTO campagne (camp_rfa, camp_lb, camp_com_lb, camp_deb_dt, camp_fin_dt, camp_crea_dt, camp_uti_crea_lb, camp_uti_crea_log, camp_modif_dt, camp_uti_modif_lb, camp_uti_modif_log) VALUES ('2015', '2015', NULL, '2015-01-01', NULL, '2015-12-31', 'création jdd usagers', 'création jdd usagers', NULL, NULL, NULL);
--INSERT INTO campagne (camp_rfa, camp_lb, camp_com_lb, camp_deb_dt, camp_fin_dt, camp_crea_dt, camp_uti_crea_lb, camp_uti_crea_log, camp_modif_dt, camp_uti_modif_lb, camp_uti_modif_log) VALUES ('ALL', 'ALL', NULL, '2010-01-01', NULL, '2017-12-31', 'création jdd usagers', 'création jdd usagers', NULL, NULL, NULL);



